### ISSUE TITLE
Add functions blocks

### ISSUE THREAD

**Issue by MoritzO02** [eclipse-4diac/4diac-forte#174]
Add .cpp and .h files that are not yet in the repo, that have already been developed. 
With the needed changegs to CMakeLists.txt and processinterface.cpp

**Comment by MartinMelikMerkumians** [comment]
Sorry, but issues are not meant as personal todo items

**Comment by diplfranzhoepfinger** [comment]
Yes. Need better Descriptions for issue. I wanted to have a Issue to connect the PR of Forte and IDE. Bit I totally agree that the Description must be more descriptive.
