### ISSUE TITLE
Problem when exporting CFBs with IO blocks

### ISSUE THREAD

**Issue by MandKastner** [eclipse-4diac/4diac-forte#220]
there is a Problem with Composite FBs. 

`    forte::core::CInternalFB<FORTE_IX> fb_IX;`

it then does not find the 

`#include "IX_fbt.h"`

and if you specifiy the Path in CMakeList.txt, 

then it does not find the 

`#include "processinterface.h"`

and if you specifiy this Path  as well in CMakeList.txt, 

then it does not link. 

maybe it is a bit special to have a IX in a Composite FB, but maybe this points to a special Error, which should be solved anyhow. 

thanks, 
Franz

_Originally posted by @diplfranzhoepfinger in https://github.com/eclipse-4diac/4diac-ide/issues/360#issuecomment-2312753296_

**Comment by diplfranzhoepfinger** [comment]
see Example here: 

[https://github.com/Meisterschulen-am-Ostbahnhof-Munchen/4diac_training1/blob/feature/lib/Ventilsteuerung/4diacIDE-workspace/test/Type%20Library/io/io_adp/IXP.fbt](https://github.com/Meisterschulen-am-Ostbahnhof-Munchen/4diac_training1/blob/feature/lib/Ventilsteuerung/4diacIDE-workspace/test/Type%20Library/io/io_adp/IXP.fbt)

and here: 

https://github.com/Meisterschulen-am-Ostbahnhof-Munchen/4diac_training1/blob/feature/lib/Ventilsteuerung/4diacIDE-workspace/test/Type%20Library/io/io_adp/QXP.fbt

**Comment by mx990** [comment]
This is a https://github.com/eclipse-4diac/4diac-forte issue. @azoitl Maybe [transfer](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository) the issue there?

I have created a PR https://github.com/eclipse-4diac/4diac-forte/pull/219 to add the missing include path for the `IX_fbt.h` (and others) in `src/stdfblib/io`. When defining a `processinterface.h`, the current source directory also needs to be in the include path, see [src/core/io/CMakeLists.txt:26](https://github.com/eclipse-4diac/4diac-forte/blob/7e8068ceb76c9abf3a5596fb45a046bd6bfdee62/src/core/io/CMakeLists.txt#L26) for an example.

I then also encountered a linker error at first, but deleting the build folder ultimately resolved it. I hope this helps.

**Comment by azoitl** [comment]
@mx990 just transferred it. 

Thx for the fix. This a very nice workaround for now. In the long run (i.e., read when I find time) I want the `processinterface.h` to die.  Most probably this will only happen for modular IO but especially for modular IO the current solution is unnecessary complex and inefficient.

**Comment by franz-hoepfinger-4diac** [comment]
this is solved to my Knowledge, right ?

**Comment by azoitl** [comment]
To my understanding yes.
