### ISSUE TITLE
how to handle fast incomming external events with different data?

### ISSUE THREAD

**Issue by cochicde** [eclipse-4diac/4diac-forte#280]
While working on the external events and how they are handled, I realized that some information might be missed and I'm not sure if that's the desired behaviour.

When an external event arrives, let's say though communication, the handler will call `recvData` on the communication layer, which usually copies the `raw` data into the `SDs` of the FB or into a buffer (at least in the opcua layer). 
The handler will then start a new chain event, which when processed, will trigger the output event and use the SDs. This decoupling between the copy of the raw data into the `SDs` and the time when the output event is actually triggered can cause different behaviour if during these two points in time more data arrives, overwriting the `SDs`, triggering the output event twice with the same data (the last one) instead of triggering one with each data. 

Is this the actual desired behaviour? Shouldn't the commucation layers (or some other component) hold a list of the incoming data and use this when triggering the output event?

**Comment by azoitl** [comment]
Yes it should. There is a proposal for the 3rd edition of IEC 61499 for how to best implement that. I can send a copy for review to you in a private message. @MandKastner is working on this topic as part of his Bachelor thesis.

**Comment by cochicde** [comment]
Oh nice! I'll be glad take a look, yes. 

I will close this issue then, as it's not properly defined in the standard yet and it can be reopened once it's being implemented.
